version: '3'
services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: intershop-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    image: service-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershop-db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
    networks:
      - app_network
    depends_on:
      - postgres

networks:
  app_network: