server:
  port: 8080

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# App
spring:
  application:
    name: intershop
  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true

  thymeleaf:
    encoding: UTF-8
    mode: HTML

  # Datasource (reactive)
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop-db
    username: postgres
    password: postgres

  # Cache
  cache:
    type: redis
    redis:
      time-to-live: 60000 # 1 минута

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

# Payment service
payment-app:
  host: localhost
  port: 8081

logging:
  level:
    sql: debug
    web: trace